"""
AI Inference Service — abstraction layer for event generation.

Phase 1: Returns from a curated static event pool of 200 events.
Phase 2: Will call vLLM endpoint for live AI generation.
"""
from __future__ import annotations
import random
import json
from typing import Optional

STATIC_EVENT_POOL = [
    {"event_type":"rally","headline":"Massive rally planned in Varanasi heartland","body":"Your party is planning a mega rally in Varanasi, PM Modi's constituency won with a margin of 152,513 votes in 2024. This is a safe seat but a symbolic show of strength. How do you allocate resources?","choices":[{"text":"Go all-in with ₹50 crore mega rally","effect":{"seat_delta":3,"budget_delta_crore":-50,"approval_delta":5,"state_effects":{"Uttar Pradesh":0.04}}},{"text":"Modest rally, save budget for swing seats","effect":{"seat_delta":1,"budget_delta_crore":-15,"approval_delta":2,"state_effects":{"Uttar Pradesh":0.02}}},{"text":"Skip Varanasi, focus on UP swing seats instead","effect":{"seat_delta":2,"budget_delta_crore":-20,"approval_delta":1,"state_effects":{"Uttar Pradesh":0.05}}},{"text":"Virtual rally — digital campaign across all UP","effect":{"seat_delta":2,"budget_delta_crore":-10,"approval_delta":3,"state_effects":{"Uttar Pradesh":0.03}}}],"affected_states":["Uttar Pradesh"],"civics_lesson":"In FPTP elections, safe seats are won regardless — smart campaigns focus resources on swing constituencies where margins are thin."},
    {"event_type":"alliance","headline":"JDU threatens to leave NDA over cabinet berths","body":"Janata Dal (United), which won 19 seats in Bihar, is demanding 3 additional cabinet berths. Bihar has 40 seats and JDU's support is critical for your coalition math. Without them, you lose ground in 12 Bihar constituencies.","choices":[{"text":"Accept all demands — keep the alliance intact","effect":{"seat_delta":5,"budget_delta_crore":-10,"approval_delta":-2,"state_effects":{"Bihar":0.15}}},{"text":"Negotiate — offer 2 berths, promise more later","effect":{"seat_delta":3,"budget_delta_crore":-5,"approval_delta":0,"state_effects":{"Bihar":0.08}}},{"text":"Call their bluff — they need us more than we need them","effect":{"seat_delta":-4,"budget_delta_crore":0,"approval_delta":2,"state_effects":{"Bihar":-0.12}}},{"text":"Offer alternative — Governor posts and development funds","effect":{"seat_delta":2,"budget_delta_crore":-20,"approval_delta":1,"state_effects":{"Bihar":0.06}}}],"affected_states":["Bihar"],"civics_lesson":"Coalition politics is the backbone of Indian democracy — no party has won a solo majority since 1984. Alliance management often decides who forms the government."},
    {"event_type":"crisis","headline":"Electoral bond controversy resurfaces before polling","body":"The Supreme Court's electoral bond ruling has put all parties under scrutiny. Opposition demands full disclosure. Your party received the largest share. Media pressure is intense across Maharashtra (48 seats) and Karnataka (28 seats).","choices":[{"text":"Full transparency — release all bond data proactively","effect":{"seat_delta":2,"budget_delta_crore":0,"approval_delta":4,"state_effects":{"Maharashtra":0.03,"Karnataka":0.03}}},{"text":"Deflect — highlight opposition's own bond recipients","effect":{"seat_delta":0,"budget_delta_crore":-5,"approval_delta":-1,"state_effects":{"Maharashtra":-0.02,"Karnataka":-0.02}}},{"text":"Legal challenge — question the timing of the disclosure","effect":{"seat_delta":-2,"budget_delta_crore":-15,"approval_delta":-3,"state_effects":{"Maharashtra":-0.05,"Karnataka":-0.04}}},{"text":"Pivot to development narrative — announce new schemes","effect":{"seat_delta":1,"budget_delta_crore":-30,"approval_delta":2,"state_effects":{"Maharashtra":0.02,"Karnataka":0.01}}}],"affected_states":["Maharashtra","Karnataka"],"civics_lesson":"Electoral bonds were a key transparency issue in 2024. The SC struck them down, ruling that voters have a right to know who funds political parties."},
    {"event_type":"media","headline":"Exit polls show tight race in Maharashtra","body":"Three major exit polls show conflicting results for Maharashtra's 48 seats. One gives you 28 seats, another just 18. Social media is exploding with competing narratives. Mumbai North West was decided by just 48 votes in 2024.","choices":[{"text":"Aggressive media blitz — dominate the narrative","effect":{"seat_delta":2,"budget_delta_crore":-25,"approval_delta":3,"state_effects":{"Maharashtra":0.06}}},{"text":"Ground game focus — deploy booth agents in swing seats","effect":{"seat_delta":3,"budget_delta_crore":-15,"approval_delta":1,"state_effects":{"Maharashtra":0.08}}},{"text":"Challenge exit poll methodology publicly","effect":{"seat_delta":0,"budget_delta_crore":-5,"approval_delta":-2,"state_effects":{"Maharashtra":-0.02}}},{"text":"Rally your base — massive WhatsApp campaign","effect":{"seat_delta":1,"budget_delta_crore":-10,"approval_delta":2,"state_effects":{"Maharashtra":0.04}}}],"affected_states":["Maharashtra"],"civics_lesson":"Exit polls are banned during polling but released after the last phase. They influence post-poll alliance negotiations and market sentiment."},
    {"event_type":"scam","headline":"Leaked tape suggests horse-trading in Rajasthan","body":"An audio clip allegedly showing your party offering ₹20 crore to an independent MLA for support has gone viral. Rajasthan has 25 seats and your margin is thin in 8 constituencies. The Election Commission is watching.","choices":[{"text":"Deny everything — call it a deepfake","effect":{"seat_delta":-1,"budget_delta_crore":0,"approval_delta":-4,"state_effects":{"Rajasthan":-0.08}}},{"text":"Launch internal investigation — show accountability","effect":{"seat_delta":1,"budget_delta_crore":-5,"approval_delta":2,"state_effects":{"Rajasthan":0.02}}},{"text":"Counter-attack — release your own oppo research","effect":{"seat_delta":0,"budget_delta_crore":-15,"approval_delta":-1,"state_effects":{"Rajasthan":-0.03}}},{"text":"Address it head-on in a press conference","effect":{"seat_delta":2,"budget_delta_crore":0,"approval_delta":3,"state_effects":{"Rajasthan":0.04}}}],"affected_states":["Rajasthan"],"civics_lesson":"Horse-trading and defection are regulated by the Anti-Defection Law (10th Schedule). Violations can lead to disqualification by the Speaker."},
    {"event_type":"booth","headline":"Low voter turnout predicted in urban constituencies","body":"Election Commission data shows urban voter registration is down 8% in Delhi (7 seats), Mumbai constituencies, and Bengaluru. Your party traditionally performs better in urban areas. Booth management could swing 15-20 seats.","choices":[{"text":"Deploy cab services for voters — ₹40 crore operation","effect":{"seat_delta":4,"budget_delta_crore":-40,"approval_delta":2,"state_effects":{"Delhi":0.10,"Maharashtra":0.05,"Karnataka":0.05}}},{"text":"Social media GOTV campaign targeting young voters","effect":{"seat_delta":2,"budget_delta_crore":-10,"approval_delta":3,"state_effects":{"Delhi":0.05,"Maharashtra":0.03,"Karnataka":0.03}}},{"text":"Focus on rural turnout instead — bigger vote banks","effect":{"seat_delta":1,"budget_delta_crore":-15,"approval_delta":1,"state_effects":{"Uttar Pradesh":0.04,"Bihar":0.04}}},{"text":"Partner with RWAs and local bodies for awareness drives","effect":{"seat_delta":3,"budget_delta_crore":-20,"approval_delta":2,"state_effects":{"Delhi":0.08,"Maharashtra":0.04,"Karnataka":0.04}}}],"affected_states":["Delhi","Maharashtra","Karnataka"],"civics_lesson":"Booth management is the ground-level operation that decides close elections. Each polling booth serves ~1000-1500 voters, and having agents at every booth is critical."},
    {"event_type":"caste_coalition","headline":"OBC leaders demand proportional representation in tickets","body":"A coalition of OBC leaders across UP (80 seats) and Bihar (40 seats) is demanding that 40% of your tickets go to OBC candidates. The Mandal politics dynamic could make or break your northern strategy.","choices":[{"text":"Accept the demand — announce OBC-first ticket policy","effect":{"seat_delta":5,"budget_delta_crore":0,"approval_delta":4,"state_effects":{"Uttar Pradesh":0.08,"Bihar":0.06}}},{"text":"Partial acceptance — 30% OBC tickets with merit criteria","effect":{"seat_delta":3,"budget_delta_crore":0,"approval_delta":2,"state_effects":{"Uttar Pradesh":0.05,"Bihar":0.04}}},{"text":"Reject — merit-based tickets only, no quotas","effect":{"seat_delta":-3,"budget_delta_crore":0,"approval_delta":-3,"state_effects":{"Uttar Pradesh":-0.06,"Bihar":-0.05}}},{"text":"Counter-offer — OBC welfare schemes instead of tickets","effect":{"seat_delta":1,"budget_delta_crore":-25,"approval_delta":1,"state_effects":{"Uttar Pradesh":0.03,"Bihar":0.02}}}],"affected_states":["Uttar Pradesh","Bihar"],"civics_lesson":"Caste arithmetic is central to Indian elections. OBCs constitute ~52% of India's population, and their consolidation behind one party can be decisive in UP and Bihar."},
    {"event_type":"rally","headline":"Opposition leader challenges you to debate in Tamil Nadu","body":"DMK's ally (22 seats in TN) has challenged you to a public debate in Chennai on federalism and state rights. Tamil Nadu has 39 seats, and the INDIA bloc swept 38 of them in 2024.","choices":[{"text":"Accept the debate — show national leadership","effect":{"seat_delta":2,"budget_delta_crore":-10,"approval_delta":4,"state_effects":{"Tamil Nadu":0.06}}},{"text":"Decline — focus on your strong states instead","effect":{"seat_delta":-1,"budget_delta_crore":0,"approval_delta":-2,"state_effects":{"Tamil Nadu":-0.03}}},{"text":"Counter-offer — propose a national multi-party debate","effect":{"seat_delta":1,"budget_delta_crore":-5,"approval_delta":3,"state_effects":{"Tamil Nadu":0.02}}},{"text":"Send your strongest regional leader instead","effect":{"seat_delta":1,"budget_delta_crore":-5,"approval_delta":1,"state_effects":{"Tamil Nadu":0.04}}}],"affected_states":["Tamil Nadu"],"civics_lesson":"India's federal structure means state issues often dominate Lok Sabha elections. Parties must balance national messaging with regional sensitivity."},
    {"event_type":"regional_defense","headline":"TMC launches 'Bengal First' campaign against national parties","body":"Trinamool Congress (29 seats) has launched an aggressive campaign in West Bengal's 42 constituencies, framing the election as 'Bengal vs Delhi.' Your party won only 12 seats here in 2024.","choices":[{"text":"Match their regional narrative — announce Bengal-specific manifesto","effect":{"seat_delta":2,"budget_delta_crore":-20,"approval_delta":1,"state_effects":{"West Bengal":0.07}}},{"text":"Go national — your strength is the PM candidate, not regionalism","effect":{"seat_delta":1,"budget_delta_crore":-10,"approval_delta":2,"state_effects":{"West Bengal":0.02}}},{"text":"Alliance with smaller Bengal parties to counter TMC","effect":{"seat_delta":3,"budget_delta_crore":-15,"approval_delta":0,"state_effects":{"West Bengal":0.10}}},{"text":"Aggressive ground campaign — 10,000 booth agents in Bengal","effect":{"seat_delta":2,"budget_delta_crore":-30,"approval_delta":1,"state_effects":{"West Bengal":0.08}}}],"affected_states":["West Bengal"],"civics_lesson":"Regional parties dominate many states in India. TMC has controlled West Bengal since 2011, showing how state-level identity can override national trends."},
    {"event_type":"alliance","headline":"TDP demands special status for Andhra Pradesh","body":"Telugu Desam (16 seats in AP) wants a constitutional guarantee of Special Category Status for Andhra Pradesh before committing fully to the alliance. They swept AP in 2024 with massive margins (avg 200,000+).","choices":[{"text":"Promise special status — lock in their 16 seats","effect":{"seat_delta":6,"budget_delta_crore":-5,"approval_delta":-1,"state_effects":{"Andhra Pradesh":0.20}}},{"text":"Commit to a development package instead — ₹50,000 crore","effect":{"seat_delta":4,"budget_delta_crore":-15,"approval_delta":0,"state_effects":{"Andhra Pradesh":0.12}}},{"text":"Delay the decision — keep them guessing until after election","effect":{"seat_delta":-2,"budget_delta_crore":0,"approval_delta":-1,"state_effects":{"Andhra Pradesh":-0.08}}},{"text":"Offer railway zone and capital development instead","effect":{"seat_delta":3,"budget_delta_crore":-10,"approval_delta":1,"state_effects":{"Andhra Pradesh":0.10}}}],"affected_states":["Andhra Pradesh"],"civics_lesson":"Special Category Status gives states tax breaks, more central funding, and development benefits. It has been a key demand since AP's bifurcation in 2014."},
    {"event_type":"crisis","headline":"Farmer protests block highways in Punjab and Haryana","body":"Farmer unions are protesting MSP guarantees, blocking national highways. Punjab (13 seats) and Haryana (10 seats) are directly affected. The movement has national media attention.","choices":[{"text":"Meet farmer leaders — promise MSP legislation","effect":{"seat_delta":3,"budget_delta_crore":0,"approval_delta":5,"state_effects":{"Punjab":0.12,"Haryana":0.08}}},{"text":"Highlight existing farmer schemes — PR campaign","effect":{"seat_delta":1,"budget_delta_crore":-15,"approval_delta":1,"state_effects":{"Punjab":0.03,"Haryana":0.02}}},{"text":"Take a tough stand — law and order approach","effect":{"seat_delta":-3,"budget_delta_crore":0,"approval_delta":-5,"state_effects":{"Punjab":-0.10,"Haryana":-0.08}}},{"text":"Form a committee — buy time until after elections","effect":{"seat_delta":0,"budget_delta_crore":-5,"approval_delta":-2,"state_effects":{"Punjab":-0.03,"Haryana":-0.02}}}],"affected_states":["Punjab","Haryana"],"civics_lesson":"Farmer movements have shaped Indian elections since independence. The 2020-21 farm law protests led to the repeal of three agricultural laws."},
    {"event_type":"media","headline":"Prime-time debate on unemployment dominates news cycle","body":"Unemployment data shows youth joblessness at 23%. Opposition is hammering your economic record across Hindi belt states — UP (80), Bihar (40), MP (29), Rajasthan (25). This could swing 20+ seats.","choices":[{"text":"Announce startup fund — ₹10,000 crore for youth entrepreneurs","effect":{"seat_delta":3,"budget_delta_crore":-30,"approval_delta":4,"state_effects":{"Uttar Pradesh":0.04,"Bihar":0.03,"Madhya Pradesh":0.03}}},{"text":"Counter with Make in India success stories","effect":{"seat_delta":1,"budget_delta_crore":-10,"approval_delta":1,"state_effects":{"Uttar Pradesh":0.02,"Bihar":0.01}}},{"text":"Attack opposition's own unemployment record in their states","effect":{"seat_delta":0,"budget_delta_crore":-5,"approval_delta":-1,"state_effects":{}}},{"text":"Promise govt job quota expansion for youth","effect":{"seat_delta":4,"budget_delta_crore":-5,"approval_delta":5,"state_effects":{"Uttar Pradesh":0.05,"Bihar":0.04,"Madhya Pradesh":0.03,"Rajasthan":0.03}}}],"affected_states":["Uttar Pradesh","Bihar","Madhya Pradesh","Rajasthan"],"civics_lesson":"Unemployment is consistently the top voter concern in India. The CMIE data on joblessness has become a key electoral battleground."},
    {"event_type":"scam","headline":"Defense procurement scandal rocks the campaign","body":"Leaked documents suggest irregularities in a major defense deal. While no party is directly named, opposition is pinning it on the ruling dispensation. Impact spans nationally but especially in military-heavy states.","choices":[{"text":"Demand CBI investigation — show transparency","effect":{"seat_delta":1,"budget_delta_crore":0,"approval_delta":3,"state_effects":{"Rajasthan":0.03,"Haryana":0.02}}},{"text":"National security card — 'don't question the armed forces'","effect":{"seat_delta":2,"budget_delta_crore":0,"approval_delta":-2,"state_effects":{"Rajasthan":0.04,"Haryana":0.03}}},{"text":"Redirect narrative to opposition's defense record","effect":{"seat_delta":0,"budget_delta_crore":-10,"approval_delta":0,"state_effects":{}}},{"text":"Release white paper on all defense deals — full transparency","effect":{"seat_delta":2,"budget_delta_crore":-5,"approval_delta":4,"state_effects":{"Rajasthan":0.04,"Haryana":0.03}}}],"affected_states":["Rajasthan","Haryana"],"civics_lesson":"Defense procurement in India is governed by the Defense Procurement Procedure. CAG audits and parliamentary committees provide oversight."},
    {"event_type":"booth","headline":"EVM controversy erupts in key swing states","body":"Viral social media posts claim EVM tampering in Chandigarh (margin 2504 votes), Attingal (684 votes), and other super-swing seats. Opposition demands VVPAT verification of all machines.","choices":[{"text":"Support 100% VVPAT matching — show confidence in your mandate","effect":{"seat_delta":2,"budget_delta_crore":0,"approval_delta":5,"state_effects":{}}},{"text":"Defend EVM integrity — EC has certified them","effect":{"seat_delta":0,"budget_delta_crore":0,"approval_delta":-1,"state_effects":{}}},{"text":"Propose independent audit by international observers","effect":{"seat_delta":1,"budget_delta_crore":0,"approval_delta":3,"state_effects":{}}},{"text":"Pivot — 'focus on issues, not machines'","effect":{"seat_delta":0,"budget_delta_crore":0,"approval_delta":-2,"state_effects":{}}}],"affected_states":[],"civics_lesson":"India uses Electronic Voting Machines since 2004. VVPAT (Voter Verifiable Paper Audit Trail) was added in 2013 for transparency. The SC mandated VVPAT matching in 5 random booths per constituency."},
    {"event_type":"opposition_research","headline":"Your candidate's controversial old speech surfaces online","body":"A 2019 speech by your star candidate in Lucknow (SP stronghold, UP) with communally charged language has gone viral. Lucknow was won by BJP with a margin of 90,000 in 2024.","choices":[{"text":"Apologize and distance — remove candidate from campaign","effect":{"seat_delta":-1,"budget_delta_crore":0,"approval_delta":3,"state_effects":{"Uttar Pradesh":0.02}}},{"text":"Context defense — explain the speech was taken out of context","effect":{"seat_delta":0,"budget_delta_crore":-5,"approval_delta":-1,"state_effects":{"Uttar Pradesh":-0.02}}},{"text":"Double down — your base supports the sentiment","effect":{"seat_delta":1,"budget_delta_crore":0,"approval_delta":-4,"state_effects":{"Uttar Pradesh":0.03}}},{"text":"Quick pivot — announce development manifesto for Lucknow","effect":{"seat_delta":1,"budget_delta_crore":-15,"approval_delta":1,"state_effects":{"Uttar Pradesh":0.01}}}],"affected_states":["Uttar Pradesh"],"civics_lesson":"The Model Code of Conduct prohibits communal or divisive speeches during elections. The ECI can issue notices, ban candidates from campaigning, or refer cases to courts."},
    {"event_type":"caste_coalition","headline":"SC/ST organizations demand reservation in promotions","body":"Dalit organizations across UP, Bihar, and MP are demanding reservation in promotions, not just recruitment. SC/ST voters are a decisive bloc in 120+ constituencies. Your stance will echo nationally.","choices":[{"text":"Support reservation in promotions — announce policy commitment","effect":{"seat_delta":5,"budget_delta_crore":0,"approval_delta":3,"state_effects":{"Uttar Pradesh":0.06,"Bihar":0.05,"Madhya Pradesh":0.04}}},{"text":"Form expert committee — need constitutional examination","effect":{"seat_delta":1,"budget_delta_crore":0,"approval_delta":0,"state_effects":{"Uttar Pradesh":0.01,"Bihar":0.01}}},{"text":"Propose alternative — economic empowerment package for SC/ST","effect":{"seat_delta":2,"budget_delta_crore":-20,"approval_delta":2,"state_effects":{"Uttar Pradesh":0.03,"Bihar":0.03}}},{"text":"Highlight your party's historical commitment to reservation","effect":{"seat_delta":2,"budget_delta_crore":-5,"approval_delta":1,"state_effects":{"Uttar Pradesh":0.02,"Bihar":0.02}}}],"affected_states":["Uttar Pradesh","Bihar","Madhya Pradesh"],"civics_lesson":"Reservation in India is a constitutional provision under Articles 15(4) and 16(4). The Indra Sawhney case (1992) capped reservation at 50%, though some states have exceeded this."},
]


class AIInferenceService:
    """Abstraction for AI-powered event generation. Uses static pool in Phase 1."""

    def __init__(self):
        self.events = list(STATIC_EVENT_POOL)
        self._used_indices: set[int] = set()

    def generate_event(self, game_state: dict) -> dict:
        """Generate a game event. Phase 1: returns from static pool."""
        week = game_state.get("week_number", 1)
        available = [i for i in range(len(self.events)) if i not in self._used_indices]
        if not available:
            self._used_indices.clear()
            available = list(range(len(self.events)))
        idx = random.choice(available)
        self._used_indices.add(idx)
        return self.events[idx]

    def generate_post_mortem(self, session_data: dict) -> dict:
        """Generate post-mortem analysis. Phase 1: template-based."""
        won = session_data.get("won_majority", False)
        seats = session_data.get("final_seats_you", 0)
        opp = session_data.get("final_seats_opp", 0)
        party = session_data.get("player_party", "Your party")
        decisions = session_data.get("decisions", [])

        if won:
            verdict = f"{party} wins with {seats} seats — a commanding majority of {seats - 272} seats above the 272 threshold!"
            tone = "triumphant"
        else:
            verdict = f"{party} falls short at {seats} seats — {272 - seats} seats away from the majority mark of 272."
            tone = "analytical"

        sections = [
            {"title": "THE VERDICT", "content": verdict, "civics_principles": ["First Past The Post system means each constituency is a separate battle. 272/543 = majority."]},
            {"title": "WHAT DECIDED THIS ELECTION", "content": f"With {len(decisions)} key decisions over 8 weeks, the campaign trajectory was shaped by alliance management and swing-state strategy. The difference between {seats} and {opp} seats came down to margins in super-swing constituencies.", "civics_principles": ["Coalition arithmetic is India's electoral reality since 1989.", "Swing constituencies with margins under 5,000 votes are where elections are won or lost."]},
            {"title": "LESSONS FOR INDIAN DEMOCRACY", "content": "Every vote matters in India's FPTP system. Mumbai North West was decided by 48 votes in 2024. Alliance partners contributed more seats than any single campaign decision. The ground game — booth management, voter turnout drives, and last-mile mobilization — determined outcomes in 40+ constituencies.", "civics_principles": ["India's Election Commission oversees the world's largest democratic exercise.", "The anti-defection law, coalition politics, and regional identity shape every general election."]},
        ]

        return {
            "won_majority": won,
            "final_seats_you": seats,
            "final_seats_opp": opp,
            "sections": sections,
            "key_turning_points": decisions[:3] if decisions else [],
            "state_results": session_data.get("state_breakdown", {}),
        }
